# Generated by Django 3.1 on 2020-08-29 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contet',
            name='users_like',
            field=models.ManyToManyField(blank=True, default=0, related_name='contents_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
